### ISSUE TITLE
Incorrect size of P in update_P causes Matlab to crash

### ISSUE THREAD

**Issue by gjosipovic** [oxfordcontrol/osqp-matlab#25]
Related to the issue #24 when passing matrix of incorrect size in emosqp('update_P', Px, Px_idx, Px_n) causes Matlab to crash. osqp.m checks for incorrect size of A but not for P.

**Comment by goulart-paul** [comment]
Are you using the latest version from the master branch?   If so, can you post a MWE?

**Comment by gjosipovic** [comment]
No, I accidentally installed wrong version. It doesn't crash with the latest version from the master branch. Sorry for the false alarm.
