### ISSUE TITLE
0.6.2 tag? 

### ISSUE THREAD

**Issue by traversaro** [oxfordcontrol/osqp-matlab#33]
Hi everyone, 
  as usual, thanks a lot for the amazing work done on osqp and the related software.

It seems that OSQP Matlab binaries are distributed for the recent 0.6.2 release of osqp (from https://dl.bintray.com/bstellato/generic/OSQP/0.6.2/install_osqp.m), that I guess they have been generated from https://github.com/oxfordcontrol/osqp-matlab/tree/release-0.6.2 . Do you think it could make sense to add a v0.6.2 tag (similar to the tag that were done in the past: https://github.com/oxfordcontrol/osqp-matlab/releases) to the corresponding commit, to permit user to easily use the v0.6.2 version even if the compile osqp-matlab from source?

Thanks in advance.

**Comment by bstellato** [comment]
Hi @traversaro. My bad I did not complete the merge. I just tagged `v0.6.2` and merged the PR.

By the way, thanks for the absolutely fantastic work you are doing in maintaining the osqp-eigen interface!

**Comment by traversaro** [comment]
> By the way, thanks for the absolutely fantastic work you are doing in maintaining the osqp-eigen interface!

Thanks, but the proper credits go to @GiulioRomualdi and @S-Dafarra !
