### ISSUE TITLE
CPU timings for update step

### ISSUE THREAD

**Issue by dkouzoup** [oxfordcontrol/osqp-matlab#6]
When OSQP is used within an NMPC framework where the dynamics change at each iteration, it would be very useful to return the time required for the update step in the info struct. The setup_time would be an upper bound on this timing but an exact value would be better for benchmarking purposes.

**Comment by gbanjac** [comment]
The `info` structure with timings is created in C. Maybe it makes sense to open this issue in the [main OSQP repo](https://github.com/oxfordcontrol/osqp).

**Comment by dkouzoup** [comment]
good point, will do
